### ISSUE TITLE
The backstage-plugin-todo-0.2.34.tgz is missing most of the files and gives error on RHDH

### ISSUE THREAD

**Issue by sgahlot** [davidfestal/backstage-plugins-dynamic-build#1]
The [todo frontend plugin](https://github.com/davidfestal/backstage-plugins-dynamic-build/releases/download/v1.23.4/backstage-plugin-todo-0.2.34.tgz) is missing all of the files that make it a dynamic plugin. The file size is 2.35kb. It only contains the following:
```
package/package.json
package/README.md
package/src/index.ts
```

Since it is missing all of the critical files, e.g. `dist-scalprum`, I'm getting the following error in RHDH console:
```
initializeRemotePlugins.ts:23 Failed to load plugin backstage.plugin-todo
...
DynamicRoot.tsx:212 Plugin backstage.plugin-todo is not configured properly: PluginRoot.EntityTodoContent not found, ignoring mountPoint: "entity.page.overview/cards"
```

When I built the todo frontend plugin from backstage clone using the following command, it worked fine in my local Janus codebase:
```
npx --yes @janus-idp/cli@1.8.1 package export-dynamic-plugin --embed-as-dependencies --dev --dynamic-plugins-root $LOCAL_DYNAMIC_PLUGIN_ROOT_DIR
```

**Comment by davidfestal** [comment]
I don't know what was the reason for this,but after regenerating the release assets, it doesn't seem to be the case anymore.
@sgahlot Do you confirm that it works now ?
If it's the case could you close the issue ?

**Comment by sgahlot** [comment]
Yes, the next build (or GitHub actions) fixed the issue and the artifact had all the necessary files. Closing the issue.
